const isoCurrencies = [
  {
    value: "AED",
    name: "Jungtinių Arabų Emyratų dirhamas",
    country: "Jungtiniai Arabų Emyratai",
  },
  { value: "AFN", name: "Afganistano afganis", country: "Afganistanas" },
  { value: "ALL", name: "Albanijos lekas", country: "Albanija" },
  { value: "AMD", name: "Armėnijos dramas", country: "Armėnija" },
  {
    value: "ANG",
    name: "Nyderlandų Antilų guldenas",
    country: "Nyderlandų Antilai",
  },
  { value: "AOA", name: "Angolos kvanza", country: "Angola" },
  { value: "ARS", name: "Argentinos pesas", country: "Argentina" },
  { value: "AUD", name: "Australijos doleris", country: "Australija" },
  { value: "AWG", name: "Arubos florinas", country: "Aruba" },
  { value: "AZN", name: "Azerbaidžano manatas", country: "Azerbaidžanas" },
  {
    value: "BAM",
    name: "Bosnijos ir Hercegovinos konvertuojamoji markė",
    country: "Bosnija ir Hercegovina",
  },
  { value: "BBD", name: "Barbadoso doleris", country: "Barbadosas" },
  { value: "BDT", name: "Bangladešo taka", country: "Bangladešas" },
  { value: "BGN", name: "Bulgarijos levas", country: "Bulgarija" },
  { value: "BHD", name: "Bahreino dinaras", country: "Bahreinas" },
  { value: "BIF", name: "Burundžio frankas", country: "Burundis" },
  { value: "BMD", name: "Bermudos doleris", country: "Bermuda" },
  { value: "BND", name: "Brunėjaus doleris", country: "Brunėjus" },
  { value: "BOB", name: "Bolivijos bolivianas", country: "Bolivija" },
  { value: "BRL", name: "Brazilijos realas", country: "Brazilija" },
  { value: "BSD", name: "Bahamų doleris", country: "Bahamai" },
  { value: "BTN", name: "Butano ngultrumas", country: "Butanas" },
  { value: "BWP", name: "Botsvanos pula", country: "Botsvana" },
  { value: "BYN", name: "Baltarusijos rublis", country: "Baltarusija" },
  { value: "BZD", name: "Belizo doleris", country: "Belizas" },
  { value: "CAD", name: "Kanados doleris", country: "Kanada" },
  {
    value: "CDF",
    name: "Kongo frankas",
    country: "Kongo Demokratinė Respublika",
  },
  { value: "CHF", name: "Šveicarijos frankas", country: "Šveicarija" },
  { value: "CLP", name: "Čilės pesas", country: "Čilė" },
  { value: "CNY", name: "Kinijos ženminbi juanis", country: "Kinija" },
  { value: "COP", name: "Kolumbijos pesas", country: "Kolumbija" },
  { value: "CRC", name: "Kosta Rikos kolonas", country: "Kosta Rika" },
  { value: "CUP", name: "Kubos pesas", country: "Kuba" },
  {
    value: "CVE",
    name: "Žaliojo Kyšulio eskudas",
    country: "Žaliasis Kyšulys",
  },
  { value: "CZK", name: "Čekijos krona", country: "Čekija" },
  { value: "DJF", name: "Džibučio frankas", country: "Džibutis" },
  { value: "DKK", name: "Danijos krona", country: "Danija" },
  { value: "DOP", name: "Dominikos pesas", country: "Dominikos Respublika" },
  { value: "DZD", name: "Alžyro dinaras", country: "Alžyras" },
  { value: "EGP", name: "Egipto svaras", country: "Egiptas" },
  { value: "ERN", name: "Eritrėjos nakfa", country: "Eritrėja" },
  { value: "ETB", name: "Etiopijos biras", country: "Etiopija" },
  { value: "EUR", name: "Euras", country: "Europos Sąjunga" },
  { value: "FJD", name: "Fidžio doleris", country: "Fidžis" },
  { value: "FKP", name: "Folklando salų svaras", country: "Folklando salos" },
  { value: "FOK", name: "Farerų salų krona", country: "Farerų salos" },
  {
    value: "GBP",
    name: "Didžiosios Britanijos svaras sterlingų",
    country: "Jungtinė Karalystė",
  },
  { value: "GEL", name: "Gruzijos laris", country: "Gruzija" },
  { value: "GGP", name: "Gernsis svaras", country: "Gernsis" },
  { value: "GHS", name: "Ganos sedis", country: "Gana" },
  { value: "GIP", name: "Gibraltaro svaras", country: "Gibraltaras" },
  { value: "GMD", name: "Gambijos dalasis", country: "Gambija" },
  { value: "GNF", name: "Gvinėjos frankas", country: "Gvinėja" },
  { value: "GTQ", name: "Gvatemalos ketcalis", country: "Gvatemala" },
  { value: "GYD", name: "Gajanos doleris", country: "Gajana" },
  { value: "HKD", name: "Honkongo doleris", country: "Honkongas" },
  { value: "HNL", name: "Hondūro lempira", country: "Hondūras" },
  { value: "HRK", name: "Kroatijos kuna", country: "Kroatija" },
  { value: "HTG", name: "Haičio gurdas", country: "Haitis" },
  { value: "HUF", name: "Vengrijos forintas", country: "Vengrija" },
  { value: "IDR", name: "Indonezijos rupija", country: "Indonezija" },
  { value: "ILS", name: "Izraelio naujasis šekelis", country: "Izraelis" },
  { value: "IMP", name: "Meno salos svaras", country: "Meno sala" },
  { value: "INR", name: "Indijos rupija", country: "Indija" },
  { value: "IQD", name: "Irako dinaras", country: "Irakas" },
  { value: "IRR", name: "Irano rialas", country: "Iranas" },
  { value: "ISK", name: "Islandijos krona", country: "Islandija" },
  { value: "JEP", name: "Džersio svaras", country: "Džersis" },
  { value: "JMD", name: "Jamaikos doleris", country: "Jamaika" },
  { value: "JOD", name: "Jordanijos dinaras", country: "Jordanija" },
  { value: "JPY", name: "Japonijos jena", country: "Japonija" },
  { value: "KES", name: "Kenijos šilingas", country: "Kenija" },
  { value: "KGS", name: "Kirgizijos somas", country: "Kirgizija" },
  { value: "KHR", name: "Kambodžos rielis", country: "Kambodža" },
  { value: "KID", name: "Kiribačio doleris", country: "Kiribatis" },
  { value: "KMF", name: "Komorų frankas", country: "Komorai" },
  { value: "KRW", name: "Pietų Korėjos vonas", country: "Pietų Korėja" },
  { value: "KWD", name: "Kuveito dinaras", country: "Kuveitas" },
  { value: "KYD", name: "Kaimanų salų doleris", country: "Kaimanų salos" },
  { value: "KZT", name: "Kazachstano tengė", country: "Kazachstanas" },
  { value: "LAK", name: "Laoso kipas", country: "Laosas" },
  { value: "LBP", name: "Libano svaras", country: "Libanas" },
  { value: "LKR", name: "Šri Lankos rupija", country: "Šri Lanka" },
  { value: "LRD", name: "Liberijos doleris", country: "Liberija" },
  { value: "LSL", name: "Lesoto lotis", country: "Lesotas" },
  { value: "LYD", name: "Libijos dinaras", country: "Libija" },
  { value: "MAD", name: "Maroko dirhamas", country: "Marokas" },
  { value: "MDL", name: "Moldovos lėja", country: "Moldova" },
  { value: "MGA", name: "Madagaskaro ariaris", country: "Madagaskaras" },
  {
    value: "MKD",
    name: "Šiaurės Makedonijos denaras",
    country: "Šiaurės Makedonija",
  },
  { value: "MMK", name: "Mianmaro kjatas", country: "Mianmaras" },
  { value: "MNT", name: "Mongolijos tugrikas", country: "Mongolija" },
  { value: "MOP", name: "Makao pataka", country: "Makao" },
  { value: "MRU", name: "Mauritanijos ugija", country: "Mauritanija" },
  { value: "MUR", name: "Mauricijaus rupija", country: "Mauricijus" },
  { value: "MVR", name: "Maldyvų rufija", country: "Maldyvai" },
  { value: "MWK", name: "Malavio kvača", country: "Malavis" },
  { value: "MXN", name: "Meksikos pesas", country: "Meksika" },
  { value: "MYR", name: "Malaizijos ringitas", country: "Malaizija" },
  { value: "MZN", name: "Mozambiko metikalis", country: "Mozambikas" },
  { value: "NAD", name: "Namibijos doleris", country: "Namibija" },
  { value: "NGN", name: "Nigerijos naira", country: "Nigerija" },
  { value: "NIO", name: "Nikaragvos kordoba", country: "Nikaragva" },
  { value: "NOK", name: "Norvegijos krona", country: "Norvegija" },
  { value: "NPR", name: "Nepalo rupija", country: "Nepalas" },
  {
    value: "NZD",
    name: "Naujosios Zelandijos doleris",
    country: "Naujoji Zelandija",
  },
  { value: "OMR", name: "Omano rialas", country: "Omanas" },
  { value: "PAB", name: "Panamos balboja", country: "Panama" },
  { value: "PEN", name: "Peru solis", country: "Peru" },
  {
    value: "PGK",
    name: "Papua Naujosios Gvinėjos kina",
    country: "Papua Naujoji Gvinėja",
  },
  { value: "PHP", name: "Filipinų pesas", country: "Filipinai" },
  { value: "PKR", name: "Pakistano rupija", country: "Pakistanas" },
  { value: "PLN", name: "Lenkijos zlotas", country: "Lenkija" },
  { value: "PYG", name: "Paragvajaus guaranis", country: "Paragvajus" },
  { value: "QAR", name: "Kataro rialas", country: "Kataras" },
  { value: "RON", name: "Rumunijos lėja", country: "Rumunija" },
  { value: "RSD", name: "Serbijos dinaras", country: "Serbija" },
  { value: "RUB", name: "Rusijos rublis", country: "Rusija" },
  { value: "RWF", name: "Ruandos frankas", country: "Ruanda" },
  { value: "SAR", name: "Saudo Arabijos rialas", country: "Saudo Arabija" },
  { value: "SBD", name: "Saliamono salų doleris", country: "Saliamono salos" },
  { value: "SCR", name: "Seišelių rupija", country: "Seišeliai" },
  { value: "SDG", name: "Sudano svaras", country: "Sudanas" },
  { value: "SEK", name: "Švedijos krona", country: "Švedija" },
  { value: "SGD", name: "Singapūro doleris", country: "Singapūras" },
  { value: "SHP", name: "Šv. Elenos salos svaras", country: "Šv. Elenos sala" },
  { value: "SLE", name: "Siera Leonės leonė", country: "Siera Leonė" },
  { value: "SOS", name: "Somalio šilingas", country: "Somalis" },
  { value: "SRD", name: "Surinamo doleris", country: "Surinamas" },
  { value: "SSP", name: "Pietų Sudano svaras", country: "Pietų Sudanas" },
  {
    value: "STN",
    name: "San Tomė ir Prinsipės dobra",
    country: "San Tomė ir Prinsipė",
  },
  { value: "SYP", name: "Sirijos svaras", country: "Sirija" },
  { value: "SZL", name: "Svazilando lilangenis", country: "Eswatinis" },
  { value: "THB", name: "Tailando batas", country: "Tailandas" },
  { value: "TJS", name: "Tadžikistano somonis", country: "Tadžikistanas" },
  { value: "TMT", name: "Turkmėnistano manatas", country: "Turkmėnistanas" },
  { value: "TND", name: "Tuniso dinaras", country: "Tunisas" },
  { value: "TOP", name: "Tongos paanga", country: "Tonga" },
  { value: "TRY", name: "Turkijos lira", country: "Turkija" },
  {
    value: "TTD",
    name: "Trinidado ir Tobago doleris",
    country: "Trinidadas ir Tobagas",
  },
  { value: "TVD", name: "Tuvalu doleris", country: "Tuvalu" },
  { value: "TWD", name: "Taivano naujasis doleris", country: "Taivanas" },
  { value: "TZS", name: "Tanzanijos šilingas", country: "Tanzanija" },
  { value: "UAH", name: "Ukrainos grivina", country: "Ukraina" },
  { value: "UGX", name: "Ugandos šilingas", country: "Uganda" },
  {
    value: "USD",
    name: "JAV doleris",
    country: "Jungtinės Amerikos Valstijos",
  },
  { value: "UYU", name: "Urugvajaus pesas", country: "Urugvajus" },
  { value: "UZS", name: "Uzbekistano sumas", country: "Uzbekistanas" },
  { value: "VES", name: "Venesuelos bolivaras", country: "Venesuela" },
  { value: "VND", name: "Vietnamo dongas", country: "Vietnamas" },
  { value: "VUV", name: "Vanuatu vatu", country: "Vanuatu" },
  { value: "WST", name: "Samoa tala", country: "Samoa" },
  { value: "XAF", name: "CFA frankas BEAC", country: "CEMAC" },
  {
    value: "XCD",
    name: "Rytų Karibų doleris",
    country: "Rytų Karibų valstybių organizacija",
  },
  {
    value: "XDR",
    name: "Specialiosios skolinimosi teisės",
    country: "Tarptautinis valiutos fondas",
  },
  { value: "XOF", name: "CFA frankas BCEAO", country: "CFA" },
  {
    value: "XPF",
    name: "CFP frankas",
    country: "Prancūzijos užjūrio teritorijos",
  },
  { value: "YER", name: "Jemeno rialas", country: "Jemenas" },
  {
    value: "ZAR",
    name: "Pietų Afrikos randas",
    country: "Pietų Afrikos Respublika",
  },
  { value: "ZMW", name: "Zambijos kvača", country: "Zambija" },
  { value: "ZWL", name: "Zimbabvės doleris", country: "Zimbabvė" },
];

export default isoCurrencies;
